# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch


# Create random tensor
rand_tensor = torch.rand(size=(7, 7))
rand_tensor

tensor([[0.8840, 0.2215, 0.4817, 0.7663, 0.8287, 0.0039, 0.5427],
        [0.3134, 0.9486, 0.1801, 0.1568, 0.5939, 0.2630, 0.0728],
        [0.7266, 0.5072, 0.5464, 0.9022, 0.9352, 0.6105, 0.2035],
        [0.5128, 0.6609, 0.4390, 0.4874, 0.4744, 0.2369, 0.0848],
        [0.1602, 0.9925, 0.1857, 0.8702, 0.7779, 0.3200, 0.0374],
        [0.4210, 0.3602, 0.2954, 0.4520, 0.7507, 0.5112, 0.4883],
        [0.4037, 0.1493, 0.2381, 0.9068, 0.4395, 0.7118, 0.5416]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor

tensor2 = torch.rand(size=(1, 7))

# Perform matrix multiplication

rand_tensor.matmul(tensor2.T)

tensor([[0.5799],
        [1.2786],
        [1.4541],
        [1.4238],
        [1.0185],
        [0.9699],
        [1.2004]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
tensor1 = torch.rand(size=(7, 7))
tensor2 = torch.rand(size=(1, 7))
# Matrix multiply tensors
tensor1 @ tensor2.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [4]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU

gpu_tensor_one = torch.rand(size=(2, 3))
gpu_tensor_two = torch.rand(size=(2, 3))

gpu_tensor_one.to(device)
gpu_tensor_two.to(device)

device, gpu_tensor_one, gpu_tensor_two

('cuda',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
gpu_tensor_outcome = gpu_tensor_one @ gpu_tensor_two.T

### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
gpu_tensor_outcome.max()

# Find min
gpu_tensor_outcome.min()

tensor(0.3647)

### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
gpu_tensor_outcome.argmax()

# Find arg min
gpu_tensor_outcome.argmin()

tensor(0)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)


# Create random tensor
rand_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
rand_tensor_two = rand_tensor.squeeze()


# Print out tensors and their shapes
rand_tensor, rand_tensor_two

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))